/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.interop;

public interface NewObject_OR_StaticField {
    // <editor-fold defaultstate="collapsed" desc="Property classe">
    public static interface classe {
        boolean check_contains(org.xowl.lang.owl2.LiteralExpression elem);
        boolean user_check_add(org.xowl.lang.owl2.LiteralExpression elem);
        boolean user_check_remove(org.xowl.lang.owl2.LiteralExpression elem);
        boolean user_check_replace(org.xowl.lang.owl2.LiteralExpression oldElem, org.xowl.lang.owl2.LiteralExpression  newElem);
        void user_add(org.xowl.lang.owl2.LiteralExpression elem);
        void user_remove(org.xowl.lang.owl2.LiteralExpression elem);
        boolean inverse_check_add(org.xowl.lang.owl2.LiteralExpression elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.LiteralExpression elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.LiteralExpression oldElem, org.xowl.lang.owl2.LiteralExpression  newElem);
        void inverse_add(org.xowl.lang.owl2.LiteralExpression elem);
        void inverse_remove(org.xowl.lang.owl2.LiteralExpression elem);
    }
    classe __getImplOfclasse();
    boolean setClasse(org.xowl.lang.owl2.LiteralExpression elem);
    org.xowl.lang.owl2.LiteralExpression getClasse();
    // </editor-fold>
}
