/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface Action_OR_Query {
    // <editor-fold defaultstate="collapsed" desc="Property axioms">
    public static interface axioms {
        boolean check_contains(org.xowl.lang.owl2.Axiom elem);
        boolean user_check_add(org.xowl.lang.owl2.Axiom elem);
        boolean user_check_remove(org.xowl.lang.owl2.Axiom elem);
        boolean user_check_replace(org.xowl.lang.owl2.Axiom oldElem, org.xowl.lang.owl2.Axiom  newElem);
        void user_add(org.xowl.lang.owl2.Axiom elem);
        void user_remove(org.xowl.lang.owl2.Axiom elem);
        boolean inverse_check_add(org.xowl.lang.owl2.Axiom elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.Axiom elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.Axiom oldElem, org.xowl.lang.owl2.Axiom  newElem);
        void inverse_add(org.xowl.lang.owl2.Axiom elem);
        void inverse_remove(org.xowl.lang.owl2.Axiom elem);
    }
    axioms __getImplOfaxioms();
    boolean addAxioms(org.xowl.lang.owl2.Axiom elem);
    boolean removeAxioms(org.xowl.lang.owl2.Axiom elem);
    java.util.Collection<org.xowl.lang.owl2.Axiom> getAllAxioms();
    // </editor-fold>
}
