/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface ArithmeticOperator extends org.xowl.lang.owl2.LiteralExpression, org.xowl.lang.actions.ArithmeticOperator_OR_BinaryBooleanOperator_OR_TestOperator, org.xowl.lang.owl2.Expression {
    // <editor-fold defaultstate="collapsed" desc="Property lhs">
    boolean setLhs(org.xowl.lang.owl2.LiteralExpression elem);
    org.xowl.lang.owl2.LiteralExpression getLhsAs(org.xowl.lang.owl2.LiteralExpression type);
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Property rhs">
    boolean setRhs(org.xowl.lang.owl2.LiteralExpression elem);
    org.xowl.lang.owl2.LiteralExpression getRhsAs(org.xowl.lang.owl2.LiteralExpression type);
    // </editor-fold>
}
