/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface ArithmeticOperator_OR_BinaryBooleanOperator_OR_TestOperator {
    // <editor-fold defaultstate="collapsed" desc="Property lhs">
    public static interface lhs {
        boolean check_contains(org.xowl.lang.owl2.Expression elem);
        boolean user_check_add(org.xowl.lang.owl2.Expression elem);
        boolean user_check_remove(org.xowl.lang.owl2.Expression elem);
        boolean user_check_replace(org.xowl.lang.owl2.Expression oldElem, org.xowl.lang.owl2.Expression  newElem);
        void user_add(org.xowl.lang.owl2.Expression elem);
        void user_remove(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_add(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.Expression oldElem, org.xowl.lang.owl2.Expression  newElem);
        void inverse_add(org.xowl.lang.owl2.Expression elem);
        void inverse_remove(org.xowl.lang.owl2.Expression elem);
    }
    lhs __getImplOflhs();
    boolean setLhs(org.xowl.lang.owl2.Expression elem);
    org.xowl.lang.owl2.Expression getLhsAs(org.xowl.lang.owl2.Expression type);
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Property rhs">
    public static interface rhs {
        boolean check_contains(org.xowl.lang.owl2.Expression elem);
        boolean user_check_add(org.xowl.lang.owl2.Expression elem);
        boolean user_check_remove(org.xowl.lang.owl2.Expression elem);
        boolean user_check_replace(org.xowl.lang.owl2.Expression oldElem, org.xowl.lang.owl2.Expression  newElem);
        void user_add(org.xowl.lang.owl2.Expression elem);
        void user_remove(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_add(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.Expression oldElem, org.xowl.lang.owl2.Expression  newElem);
        void inverse_add(org.xowl.lang.owl2.Expression elem);
        void inverse_remove(org.xowl.lang.owl2.Expression elem);
    }
    rhs __getImplOfrhs();
    boolean setRhs(org.xowl.lang.owl2.Expression elem);
    org.xowl.lang.owl2.Expression getRhsAs(org.xowl.lang.owl2.Expression type);
    // </editor-fold>
}
