/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface Assign_OR_BNot_OR_Declare_OR_ExpressionElement_OR_For_OR_Return {
    // <editor-fold defaultstate="collapsed" desc="Property expression">
    public static interface expression {
        boolean check_contains(org.xowl.lang.owl2.Expression elem);
        boolean user_check_add(org.xowl.lang.owl2.Expression elem);
        boolean user_check_remove(org.xowl.lang.owl2.Expression elem);
        boolean user_check_replace(org.xowl.lang.owl2.Expression oldElem, org.xowl.lang.owl2.Expression  newElem);
        void user_add(org.xowl.lang.owl2.Expression elem);
        void user_remove(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_add(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.Expression elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.Expression oldElem, org.xowl.lang.owl2.Expression  newElem);
        void inverse_add(org.xowl.lang.owl2.Expression elem);
        void inverse_remove(org.xowl.lang.owl2.Expression elem);
    }
    expression __getImplOfexpression();
    boolean setExpression(org.xowl.lang.owl2.Expression elem);
    org.xowl.lang.owl2.Expression getExpressionAs(org.xowl.lang.owl2.Expression type);
    // </editor-fold>
}
