/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface Execution extends org.xowl.lang.actions.ArrayExpression, org.xowl.lang.actions.ExecutableExpression, org.xowl.lang.actions.FunctionExpression, org.xowl.lang.actions.Statement, org.xowl.lang.owl2.ClassExpression, org.xowl.lang.owl2.DataPropertyExpression, org.xowl.lang.owl2.Datarange, org.xowl.lang.owl2.EntityExpression, org.xowl.lang.owl2.IndividualExpression, org.xowl.lang.owl2.LiteralExpression, org.xowl.lang.owl2.ObjectPropertyExpression, org.xowl.lang.interop.JavaObjectExpression, org.xowl.lang.owl2.Expression, org.xowl.lang.owl2.Axiom_OR_Statement {
    // <editor-fold defaultstate="collapsed" desc="Property valueSeq">
    public static interface valueSeq {
        boolean check_contains(org.xowl.lang.actions.ExpressionSequenceExpression elem);
        boolean user_check_add(org.xowl.lang.actions.ExpressionSequenceExpression elem);
        boolean user_check_remove(org.xowl.lang.actions.ExpressionSequenceExpression elem);
        boolean user_check_replace(org.xowl.lang.actions.ExpressionSequenceExpression oldElem, org.xowl.lang.actions.ExpressionSequenceExpression  newElem);
        void user_add(org.xowl.lang.actions.ExpressionSequenceExpression elem);
        void user_remove(org.xowl.lang.actions.ExpressionSequenceExpression elem);
        boolean inverse_check_add(org.xowl.lang.actions.ExpressionSequenceExpression elem);
        boolean inverse_check_remove(org.xowl.lang.actions.ExpressionSequenceExpression elem);
        boolean inverse_check_replace(org.xowl.lang.actions.ExpressionSequenceExpression oldElem, org.xowl.lang.actions.ExpressionSequenceExpression  newElem);
        void inverse_add(org.xowl.lang.actions.ExpressionSequenceExpression elem);
        void inverse_remove(org.xowl.lang.actions.ExpressionSequenceExpression elem);
    }
    valueSeq __getImplOfvalueSeq();
    boolean setValueSeq(org.xowl.lang.actions.ExpressionSequenceExpression elem);
    org.xowl.lang.actions.ExpressionSequenceExpression getValueSeq();
    // </editor-fold>
}
