/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface FunctionAxiom extends org.xowl.lang.owl2.Axiom, org.xowl.lang.actions.FunctionAxiom_OR_Invoke, org.xowl.lang.owl2.Annotation_OR_Axiom_OR_Ontology, org.xowl.lang.owl2.Axiom_OR_Statement {
}
