/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface FunctionAxiom_OR_Invoke {
    // <editor-fold defaultstate="collapsed" desc="Property function">
    public static interface function {
        boolean check_contains(org.xowl.lang.actions.FunctionExpression elem);
        boolean user_check_add(org.xowl.lang.actions.FunctionExpression elem);
        boolean user_check_remove(org.xowl.lang.actions.FunctionExpression elem);
        boolean user_check_replace(org.xowl.lang.actions.FunctionExpression oldElem, org.xowl.lang.actions.FunctionExpression  newElem);
        void user_add(org.xowl.lang.actions.FunctionExpression elem);
        void user_remove(org.xowl.lang.actions.FunctionExpression elem);
        boolean inverse_check_add(org.xowl.lang.actions.FunctionExpression elem);
        boolean inverse_check_remove(org.xowl.lang.actions.FunctionExpression elem);
        boolean inverse_check_replace(org.xowl.lang.actions.FunctionExpression oldElem, org.xowl.lang.actions.FunctionExpression  newElem);
        void inverse_add(org.xowl.lang.actions.FunctionExpression elem);
        void inverse_remove(org.xowl.lang.actions.FunctionExpression elem);
    }
    function __getImplOffunction();
    boolean setFunction(org.xowl.lang.actions.FunctionExpression elem);
    org.xowl.lang.actions.FunctionExpression getFunction();
    // </editor-fold>
}
