/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface LoopStatement extends org.xowl.lang.actions.Statement, org.xowl.lang.actions.Block_OR_Lambda_OR_LoopStatement, org.xowl.lang.owl2.Axiom_OR_Statement {
    // <editor-fold defaultstate="collapsed" desc="Property contains">
    boolean setContains(org.xowl.lang.actions.Statement elem);
    org.xowl.lang.actions.Statement getContains();
    // </editor-fold>
}
