/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public class NewIndividual implements org.xowl.lang.owl2.IndividualExpression, org.xowl.lang.owl2.Expression {
    public NewIndividual() {
    }
    
}
