/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.actions;

public interface Predicate extends org.xowl.lang.owl2.LiteralExpression, org.xowl.lang.owl2.Expression {
}
