trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker login -u $(dockerLogin) -p $(dockerPassword)
    - task: DownloadSecureFile@1
      name: gpgKey
      inputs:
        secureFile: 'cenotelie.gpg.key'
    - task: DownloadSecureFile@1
      name: mvnSettings
      inputs:
        secureFile: 'settings.xml'
    - script: |
        cat '$(gpgPass)' | gpg --batch --import '$(gpgKey.secureFilePath)'
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        goals: 'deploy'
        options: '--settings $(mvnSettings.secureFilePath) "-Dgpg.passphrase=$(gpgPass)"'
    - task: ShellScript@2
      displayName: Build docker images
      inputs:
        scriptPath: build-docker.sh
        args: --target=integration
    - task: ShellScript@2
      displayName: Publish docker images
      inputs:
        scriptPath: build-publish.sh
        args: --target=integration