/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.infra.lang.owl2;

public interface Annotation_OR_AnnotationAssertion_OR_AnnotationPropertyDomain_OR_AnnotationPropertyRange_OR_SubAnno4 {
    // <editor-fold defaultstate="collapsed" desc="Property annotProperty">
    public static interface annotProperty {
        boolean check_contains(org.xowl.infra.lang.owl2.IRI elem);
        boolean user_check_add(org.xowl.infra.lang.owl2.IRI elem);
        boolean user_check_remove(org.xowl.infra.lang.owl2.IRI elem);
        boolean user_check_replace(org.xowl.infra.lang.owl2.IRI oldElem, org.xowl.infra.lang.owl2.IRI  newElem);
        void user_add(org.xowl.infra.lang.owl2.IRI elem);
        void user_remove(org.xowl.infra.lang.owl2.IRI elem);
        boolean inverse_check_add(org.xowl.infra.lang.owl2.IRI elem);
        boolean inverse_check_remove(org.xowl.infra.lang.owl2.IRI elem);
        boolean inverse_check_replace(org.xowl.infra.lang.owl2.IRI oldElem, org.xowl.infra.lang.owl2.IRI  newElem);
        void inverse_add(org.xowl.infra.lang.owl2.IRI elem);
        void inverse_remove(org.xowl.infra.lang.owl2.IRI elem);
    }
    annotProperty __getImplOfannotProperty();
    boolean setAnnotProperty(org.xowl.infra.lang.owl2.IRI elem);
    org.xowl.infra.lang.owl2.IRI getAnnotProperty();
    // </editor-fold>
}
