/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.infra.lang.owl2;

public interface DataIntersectionOf_OR_DataUnionOf {
    // <editor-fold defaultstate="collapsed" desc="Property datarangeSeq">
    public static interface datarangeSeq {
        boolean check_contains(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
        boolean user_check_add(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
        boolean user_check_remove(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
        boolean user_check_replace(org.xowl.infra.lang.owl2.DatarangeSequenceExpression oldElem, org.xowl.infra.lang.owl2.DatarangeSequenceExpression  newElem);
        void user_add(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
        void user_remove(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
        boolean inverse_check_add(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
        boolean inverse_check_remove(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
        boolean inverse_check_replace(org.xowl.infra.lang.owl2.DatarangeSequenceExpression oldElem, org.xowl.infra.lang.owl2.DatarangeSequenceExpression  newElem);
        void inverse_add(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
        void inverse_remove(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
    }
    datarangeSeq __getImplOfdatarangeSeq();
    boolean setDatarangeSeq(org.xowl.infra.lang.owl2.DatarangeSequenceExpression elem);
    org.xowl.infra.lang.owl2.DatarangeSequenceExpression getDatarangeSeq();
    // </editor-fold>
}
