/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.infra.lang.owl2;

public interface DifferentIndividuals_OR_ObjectOneOf_OR_SameIndividual {
    // <editor-fold defaultstate="collapsed" desc="Property individualSeq">
    public static interface individualSeq {
        boolean check_contains(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
        boolean user_check_add(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
        boolean user_check_remove(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
        boolean user_check_replace(org.xowl.infra.lang.owl2.IndividualSequenceExpression oldElem, org.xowl.infra.lang.owl2.IndividualSequenceExpression  newElem);
        void user_add(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
        void user_remove(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
        boolean inverse_check_add(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
        boolean inverse_check_remove(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
        boolean inverse_check_replace(org.xowl.infra.lang.owl2.IndividualSequenceExpression oldElem, org.xowl.infra.lang.owl2.IndividualSequenceExpression  newElem);
        void inverse_add(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
        void inverse_remove(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
    }
    individualSeq __getImplOfindividualSeq();
    boolean setIndividualSeq(org.xowl.infra.lang.owl2.IndividualSequenceExpression elem);
    org.xowl.infra.lang.owl2.IndividualSequenceExpression getIndividualSeq();
    // </editor-fold>
}
