/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.infra.lang.owl2;

public interface EntityExpression extends org.xowl.infra.lang.owl2.ClassExpression, org.xowl.infra.lang.owl2.DataPropertyExpression, org.xowl.infra.lang.owl2.Datarange, org.xowl.infra.lang.owl2.IndividualExpression, org.xowl.infra.lang.owl2.ObjectPropertyExpression, org.xowl.infra.lang.actions.FunctionExpression {
}
