/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 1.3.2.0
 */

package org.xowl.engine.loaders;

import org.xowl.hime.redist.Symbol;
import org.xowl.hime.redist.parsers.LRkAutomaton;
import org.xowl.hime.redist.parsers.LRkParser;

/**
 * Represents a parser
 */
class FunctionalOWL2Parser extends LRkParser {
    /**
     * The automaton for this parser
     */
    private static final LRkAutomaton automaton = LRkAutomaton.find(FunctionalOWL2Parser.class, "FunctionalOWL2Parser.bin");

    /**
     * Contains the constant IDs for the variables and virtuals in this parser
     */
    public static class ID {
        /**
         * The unique identifier for variable document
         */
        public static final int document = 0x0014;
        /**
         * The unique identifier for variable prefixes
         */
        public static final int prefixes = 0x0015;
        /**
         * The unique identifier for variable prefix
         */
        public static final int prefix = 0x0016;
        /**
         * The unique identifier for variable ontology
         */
        public static final int ontology = 0x0017;
        /**
         * The unique identifier for variable ontologyIRI
         */
        public static final int ontologyIRI = 0x0018;
        /**
         * The unique identifier for variable imports
         */
        public static final int imports = 0x0019;
        /**
         * The unique identifier for variable import
         */
        public static final int _import = 0x001A;
        /**
         * The unique identifier for variable elements
         */
        public static final int elements = 0x001B;
        /**
         * The unique identifier for variable element
         */
        public static final int element = 0x001C;
        /**
         * The unique identifier for variable annotations
         */
        public static final int annotations = 0x001D;
        /**
         * The unique identifier for variable annotation
         */
        public static final int annotation = 0x001E;
        /**
         * The unique identifier for variable annotationSubject
         */
        public static final int annotationSubject = 0x001F;
        /**
         * The unique identifier for variable annotationProperty
         */
        public static final int annotationProperty = 0x0020;
        /**
         * The unique identifier for variable annotationValue
         */
        public static final int annotationValue = 0x0021;
        /**
         * The unique identifier for variable iri
         */
        public static final int iri = 0x0022;
        /**
         * The unique identifier for variable individual
         */
        public static final int individual = 0x0023;
        /**
         * The unique identifier for variable namedIndividual
         */
        public static final int namedIndividual = 0x0024;
        /**
         * The unique identifier for variable anonymousIndividual
         */
        public static final int anonymousIndividual = 0x0025;
        /**
         * The unique identifier for variable literal
         */
        public static final int literal = 0x0026;
        /**
         * The unique identifier for variable literalTyped
         */
        public static final int literalTyped = 0x0027;
        /**
         * The unique identifier for variable literalString
         */
        public static final int literalString = 0x0028;
        /**
         * The unique identifier for variable literalLang
         */
        public static final int literalLang = 0x0029;
        /**
         * The unique identifier for variable expObjectProperty
         */
        public static final int expObjectProperty = 0x002A;
        /**
         * The unique identifier for variable expObjectPropertyChain
         */
        public static final int expObjectPropertyChain = 0x002B;
        /**
         * The unique identifier for variable expInverseObjectProperty
         */
        public static final int expInverseObjectProperty = 0x002C;
        /**
         * The unique identifier for variable expDataProperty
         */
        public static final int expDataProperty = 0x002D;
        /**
         * The unique identifier for variable expDatarange
         */
        public static final int expDatarange = 0x002E;
        /**
         * The unique identifier for variable expDataIntersectionOf
         */
        public static final int expDataIntersectionOf = 0x002F;
        /**
         * The unique identifier for variable expDataUnionOf
         */
        public static final int expDataUnionOf = 0x0030;
        /**
         * The unique identifier for variable expDataComplementOf
         */
        public static final int expDataComplementOf = 0x0031;
        /**
         * The unique identifier for variable expDataOneOf
         */
        public static final int expDataOneOf = 0x0032;
        /**
         * The unique identifier for variable expDatatypeRestriction
         */
        public static final int expDatatypeRestriction = 0x0033;
        /**
         * The unique identifier for variable expRestriction
         */
        public static final int expRestriction = 0x0034;
        /**
         * The unique identifier for variable expClass
         */
        public static final int expClass = 0x0035;
        /**
         * The unique identifier for variable expObjectInterfactionOf
         */
        public static final int expObjectInterfactionOf = 0x0036;
        /**
         * The unique identifier for variable expObjectUnionOf
         */
        public static final int expObjectUnionOf = 0x0037;
        /**
         * The unique identifier for variable expObjectComplementOf
         */
        public static final int expObjectComplementOf = 0x0038;
        /**
         * The unique identifier for variable expObjectOneOf
         */
        public static final int expObjectOneOf = 0x0039;
        /**
         * The unique identifier for variable expObjectSomeValuesFrom
         */
        public static final int expObjectSomeValuesFrom = 0x003A;
        /**
         * The unique identifier for variable expObjectAllValuesFrom
         */
        public static final int expObjectAllValuesFrom = 0x003B;
        /**
         * The unique identifier for variable expObjectHasValue
         */
        public static final int expObjectHasValue = 0x003C;
        /**
         * The unique identifier for variable expObjectHasSelf
         */
        public static final int expObjectHasSelf = 0x003D;
        /**
         * The unique identifier for variable expObjectMinCardinality
         */
        public static final int expObjectMinCardinality = 0x003E;
        /**
         * The unique identifier for variable expObjectMaxCardinality
         */
        public static final int expObjectMaxCardinality = 0x003F;
        /**
         * The unique identifier for variable expObjectExactCardinality
         */
        public static final int expObjectExactCardinality = 0x0040;
        /**
         * The unique identifier for variable expDataSomeValuesFrom
         */
        public static final int expDataSomeValuesFrom = 0x0041;
        /**
         * The unique identifier for variable expDataAllValuesFrom
         */
        public static final int expDataAllValuesFrom = 0x0042;
        /**
         * The unique identifier for variable expDataHasValue
         */
        public static final int expDataHasValue = 0x0043;
        /**
         * The unique identifier for variable expDataMinCardinality
         */
        public static final int expDataMinCardinality = 0x0044;
        /**
         * The unique identifier for variable expDataMaxCardinality
         */
        public static final int expDataMaxCardinality = 0x0045;
        /**
         * The unique identifier for variable expDataExactCardinality
         */
        public static final int expDataExactCardinality = 0x0046;
        /**
         * The unique identifier for variable axiom
         */
        public static final int axiom = 0x0047;
        /**
         * The unique identifier for variable axiomDeclaration
         */
        public static final int axiomDeclaration = 0x0048;
        /**
         * The unique identifier for variable axiomClass
         */
        public static final int axiomClass = 0x0049;
        /**
         * The unique identifier for variable axiomSubClassOf
         */
        public static final int axiomSubClassOf = 0x004A;
        /**
         * The unique identifier for variable axiomEquivalentClasses
         */
        public static final int axiomEquivalentClasses = 0x004B;
        /**
         * The unique identifier for variable axiomDisjointClasses
         */
        public static final int axiomDisjointClasses = 0x004C;
        /**
         * The unique identifier for variable axiomDisjointUnion
         */
        public static final int axiomDisjointUnion = 0x004D;
        /**
         * The unique identifier for variable axiomObjectProperty
         */
        public static final int axiomObjectProperty = 0x004E;
        /**
         * The unique identifier for variable axiomSubOjectPropertyOf
         */
        public static final int axiomSubOjectPropertyOf = 0x004F;
        /**
         * The unique identifier for variable axiomEquivalentObjectProperties
         */
        public static final int axiomEquivalentObjectProperties = 0x0050;
        /**
         * The unique identifier for variable axiomDisjointObjectProperties
         */
        public static final int axiomDisjointObjectProperties = 0x0051;
        /**
         * The unique identifier for variable axiomInverseObjectProperties
         */
        public static final int axiomInverseObjectProperties = 0x0052;
        /**
         * The unique identifier for variable axiomObjectPropertyDomain
         */
        public static final int axiomObjectPropertyDomain = 0x0053;
        /**
         * The unique identifier for variable axiomObjectPropertyRange
         */
        public static final int axiomObjectPropertyRange = 0x0054;
        /**
         * The unique identifier for variable axiomFunctionalObjectProperty
         */
        public static final int axiomFunctionalObjectProperty = 0x0055;
        /**
         * The unique identifier for variable axiomInverseFunctionalObjectProperty
         */
        public static final int axiomInverseFunctionalObjectProperty = 0x0056;
        /**
         * The unique identifier for variable axiomReflexiveObjectProperty
         */
        public static final int axiomReflexiveObjectProperty = 0x0057;
        /**
         * The unique identifier for variable axiomIrreflexiveObjectProperty
         */
        public static final int axiomIrreflexiveObjectProperty = 0x0058;
        /**
         * The unique identifier for variable axiomSymmetricObjectProperty
         */
        public static final int axiomSymmetricObjectProperty = 0x0059;
        /**
         * The unique identifier for variable axiomAsymmetricObjectProperty
         */
        public static final int axiomAsymmetricObjectProperty = 0x005A;
        /**
         * The unique identifier for variable axiomTransitiveObjectProperty
         */
        public static final int axiomTransitiveObjectProperty = 0x005B;
        /**
         * The unique identifier for variable axiomDataProperty
         */
        public static final int axiomDataProperty = 0x005C;
        /**
         * The unique identifier for variable axiomSubDataPropertyOf
         */
        public static final int axiomSubDataPropertyOf = 0x005D;
        /**
         * The unique identifier for variable axiomEquivalentDataProperties
         */
        public static final int axiomEquivalentDataProperties = 0x005E;
        /**
         * The unique identifier for variable axiomDisjointDataProperties
         */
        public static final int axiomDisjointDataProperties = 0x005F;
        /**
         * The unique identifier for variable axiomDataPropertyDomain
         */
        public static final int axiomDataPropertyDomain = 0x0060;
        /**
         * The unique identifier for variable axiomDataPropertyRange
         */
        public static final int axiomDataPropertyRange = 0x0061;
        /**
         * The unique identifier for variable axiomFunctionalDataProperty
         */
        public static final int axiomFunctionalDataProperty = 0x0062;
        /**
         * The unique identifier for variable axiomDatatype
         */
        public static final int axiomDatatype = 0x0063;
        /**
         * The unique identifier for variable axiomHasKey
         */
        public static final int axiomHasKey = 0x0064;
        /**
         * The unique identifier for variable axiomHasKeyObjectProperties
         */
        public static final int axiomHasKeyObjectProperties = 0x0065;
        /**
         * The unique identifier for variable axiomHasKeyDataProperties
         */
        public static final int axiomHasKeyDataProperties = 0x0066;
        /**
         * The unique identifier for variable axiomAssertion
         */
        public static final int axiomAssertion = 0x0067;
        /**
         * The unique identifier for variable axiomSameIndividual
         */
        public static final int axiomSameIndividual = 0x0068;
        /**
         * The unique identifier for variable axiomDifferentIndividuals
         */
        public static final int axiomDifferentIndividuals = 0x0069;
        /**
         * The unique identifier for variable axiomClassAssertion
         */
        public static final int axiomClassAssertion = 0x006A;
        /**
         * The unique identifier for variable axiomObjectPropertyAssertion
         */
        public static final int axiomObjectPropertyAssertion = 0x006B;
        /**
         * The unique identifier for variable axiomNegativeObjectPropertyAssertion
         */
        public static final int axiomNegativeObjectPropertyAssertion = 0x006C;
        /**
         * The unique identifier for variable axiomDataPropertyAssertion
         */
        public static final int axiomDataPropertyAssertion = 0x006D;
        /**
         * The unique identifier for variable axiomNegativeDataPropertyAssertion
         */
        public static final int axiomNegativeDataPropertyAssertion = 0x006E;
        /**
         * The unique identifier for variable axiomAnnotation
         */
        public static final int axiomAnnotation = 0x006F;
        /**
         * The unique identifier for variable axiomAnnotationAssertion
         */
        public static final int axiomAnnotationAssertion = 0x0070;
        /**
         * The unique identifier for variable axiomSubAnnotationPropertyOf
         */
        public static final int axiomSubAnnotationPropertyOf = 0x0071;
        /**
         * The unique identifier for variable axiomAnnotationPropertyDomain
         */
        public static final int axiomAnnotationPropertyDomain = 0x0072;
        /**
         * The unique identifier for variable axiomAnnotationPropertyRange
         */
        public static final int axiomAnnotationPropertyRange = 0x0073;
        /**
         * The unique identifier for variable _Axiom_
         */
        public static final int _Axiom_ = 0x00D6;
    }

    /**
     * The collection of variables matched by this parser
     * <p/>
     * The variables are in an order consistent with the automaton,
     * so that variable indices in the automaton can be used to retrieve the variables in this table
     */
    private static final Symbol[] variables = {
            new Symbol(0x0014, "document"),
            new Symbol(0x0015, "prefixes"),
            new Symbol(0x0016, "prefix"),
            new Symbol(0x0017, "ontology"),
            new Symbol(0x0018, "ontologyIRI"),
            new Symbol(0x0019, "imports"),
            new Symbol(0x001A, "import"),
            new Symbol(0x001B, "elements"),
            new Symbol(0x001C, "element"),
            new Symbol(0x001D, "annotations"),
            new Symbol(0x001E, "annotation"),
            new Symbol(0x001F, "annotationSubject"),
            new Symbol(0x0020, "annotationProperty"),
            new Symbol(0x0021, "annotationValue"),
            new Symbol(0x0022, "iri"),
            new Symbol(0x0023, "individual"),
            new Symbol(0x0024, "namedIndividual"),
            new Symbol(0x0025, "anonymousIndividual"),
            new Symbol(0x0026, "literal"),
            new Symbol(0x0027, "literalTyped"),
            new Symbol(0x0028, "literalString"),
            new Symbol(0x0029, "literalLang"),
            new Symbol(0x002A, "expObjectProperty"),
            new Symbol(0x002B, "expObjectPropertyChain"),
            new Symbol(0x002C, "expInverseObjectProperty"),
            new Symbol(0x002D, "expDataProperty"),
            new Symbol(0x002E, "expDatarange"),
            new Symbol(0x002F, "expDataIntersectionOf"),
            new Symbol(0x0030, "expDataUnionOf"),
            new Symbol(0x0031, "expDataComplementOf"),
            new Symbol(0x0032, "expDataOneOf"),
            new Symbol(0x0033, "expDatatypeRestriction"),
            new Symbol(0x0034, "expRestriction"),
            new Symbol(0x0035, "expClass"),
            new Symbol(0x0036, "expObjectInterfactionOf"),
            new Symbol(0x0037, "expObjectUnionOf"),
            new Symbol(0x0038, "expObjectComplementOf"),
            new Symbol(0x0039, "expObjectOneOf"),
            new Symbol(0x003A, "expObjectSomeValuesFrom"),
            new Symbol(0x003B, "expObjectAllValuesFrom"),
            new Symbol(0x003C, "expObjectHasValue"),
            new Symbol(0x003D, "expObjectHasSelf"),
            new Symbol(0x003E, "expObjectMinCardinality"),
            new Symbol(0x003F, "expObjectMaxCardinality"),
            new Symbol(0x0040, "expObjectExactCardinality"),
            new Symbol(0x0041, "expDataSomeValuesFrom"),
            new Symbol(0x0042, "expDataAllValuesFrom"),
            new Symbol(0x0043, "expDataHasValue"),
            new Symbol(0x0044, "expDataMinCardinality"),
            new Symbol(0x0045, "expDataMaxCardinality"),
            new Symbol(0x0046, "expDataExactCardinality"),
            new Symbol(0x0047, "axiom"),
            new Symbol(0x0048, "axiomDeclaration"),
            new Symbol(0x0049, "axiomClass"),
            new Symbol(0x004A, "axiomSubClassOf"),
            new Symbol(0x004B, "axiomEquivalentClasses"),
            new Symbol(0x004C, "axiomDisjointClasses"),
            new Symbol(0x004D, "axiomDisjointUnion"),
            new Symbol(0x004E, "axiomObjectProperty"),
            new Symbol(0x004F, "axiomSubOjectPropertyOf"),
            new Symbol(0x0050, "axiomEquivalentObjectProperties"),
            new Symbol(0x0051, "axiomDisjointObjectProperties"),
            new Symbol(0x0052, "axiomInverseObjectProperties"),
            new Symbol(0x0053, "axiomObjectPropertyDomain"),
            new Symbol(0x0054, "axiomObjectPropertyRange"),
            new Symbol(0x0055, "axiomFunctionalObjectProperty"),
            new Symbol(0x0056, "axiomInverseFunctionalObjectProperty"),
            new Symbol(0x0057, "axiomReflexiveObjectProperty"),
            new Symbol(0x0058, "axiomIrreflexiveObjectProperty"),
            new Symbol(0x0059, "axiomSymmetricObjectProperty"),
            new Symbol(0x005A, "axiomAsymmetricObjectProperty"),
            new Symbol(0x005B, "axiomTransitiveObjectProperty"),
            new Symbol(0x005C, "axiomDataProperty"),
            new Symbol(0x005D, "axiomSubDataPropertyOf"),
            new Symbol(0x005E, "axiomEquivalentDataProperties"),
            new Symbol(0x005F, "axiomDisjointDataProperties"),
            new Symbol(0x0060, "axiomDataPropertyDomain"),
            new Symbol(0x0061, "axiomDataPropertyRange"),
            new Symbol(0x0062, "axiomFunctionalDataProperty"),
            new Symbol(0x0063, "axiomDatatype"),
            new Symbol(0x0064, "axiomHasKey"),
            new Symbol(0x0065, "axiomHasKeyObjectProperties"),
            new Symbol(0x0066, "axiomHasKeyDataProperties"),
            new Symbol(0x0067, "axiomAssertion"),
            new Symbol(0x0068, "axiomSameIndividual"),
            new Symbol(0x0069, "axiomDifferentIndividuals"),
            new Symbol(0x006A, "axiomClassAssertion"),
            new Symbol(0x006B, "axiomObjectPropertyAssertion"),
            new Symbol(0x006C, "axiomNegativeObjectPropertyAssertion"),
            new Symbol(0x006D, "axiomDataPropertyAssertion"),
            new Symbol(0x006E, "axiomNegativeDataPropertyAssertion"),
            new Symbol(0x006F, "axiomAnnotation"),
            new Symbol(0x0070, "axiomAnnotationAssertion"),
            new Symbol(0x0071, "axiomSubAnnotationPropertyOf"),
            new Symbol(0x0072, "axiomAnnotationPropertyDomain"),
            new Symbol(0x0073, "axiomAnnotationPropertyRange"),
            new Symbol(0x0074, "_gen_V116"),
            new Symbol(0x007A, "_gen_V122"),
            new Symbol(0x007C, "_gen_V124"),
            new Symbol(0x007D, "_gen_V125"),
            new Symbol(0x0081, "_gen_V129"),
            new Symbol(0x0084, "_gen_V132"),
            new Symbol(0x0086, "_gen_V134"),
            new Symbol(0x0089, "_gen_V137"),
            new Symbol(0x008B, "_gen_V139"),
            new Symbol(0x008D, "_gen_V141"),
            new Symbol(0x008F, "_gen_V143"),
            new Symbol(0x0092, "_gen_V146"),
            new Symbol(0x00A9, "_gen_V169"),
            new Symbol(0x00AB, "_gen_V171"),
            new Symbol(0x00AD, "_gen_V173"),
            new Symbol(0x00B0, "_gen_V176"),
            new Symbol(0x00B2, "_gen_V178"),
            new Symbol(0x00BF, "_gen_V191"),
            new Symbol(0x00C1, "_gen_V193"),
            new Symbol(0x00C7, "_gen_V199"),
            new Symbol(0x00C8, "_gen_V200"),
            new Symbol(0x00CA, "_gen_V202"),
            new Symbol(0x00CC, "_gen_V204"),
            new Symbol(0x00D6, "_Axiom_")};
    /**
     * The collection of virtuals matched by this parser
     * <p/>
     * The virtuals are in an order consistent with the automaton,
     * so that virtual indices in the automaton can be used to retrieve the virtuals in this table
     */
    private static final Symbol[] virtuals = {
    };

    /**
     * Initializes a new instance of the parser
     *
     * @param lexer The input lexer
     */
    public FunctionalOWL2Parser(FunctionalOWL2Lexer lexer) {
        super(automaton, variables, virtuals, null, lexer);
    }
}
