/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.infra.lang.runtime;

public interface DataCardinalityRestriction extends org.xowl.infra.lang.runtime.CardinalityRestriction, org.xowl.infra.lang.runtime.DataPropertyRestriction, org.xowl.infra.lang.runtime.DataCardinalityRestriction_OR_NAryDataPropertyRestriction {
}
