/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.infra.lang.runtime;

public interface DataPropertyAssertion_OR_DatatypeRestriction {
    // <editor-fold defaultstate="collapsed" desc="Property valueLiteral">
    public static interface valueLiteral {
        boolean check_contains(org.xowl.infra.lang.runtime.Literal elem);
        boolean user_check_add(org.xowl.infra.lang.runtime.Literal elem);
        boolean user_check_remove(org.xowl.infra.lang.runtime.Literal elem);
        boolean user_check_replace(org.xowl.infra.lang.runtime.Literal oldElem, org.xowl.infra.lang.runtime.Literal  newElem);
        void user_add(org.xowl.infra.lang.runtime.Literal elem);
        void user_remove(org.xowl.infra.lang.runtime.Literal elem);
        boolean inverse_check_add(org.xowl.infra.lang.runtime.Literal elem);
        boolean inverse_check_remove(org.xowl.infra.lang.runtime.Literal elem);
        boolean inverse_check_replace(org.xowl.infra.lang.runtime.Literal oldElem, org.xowl.infra.lang.runtime.Literal  newElem);
        void inverse_add(org.xowl.infra.lang.runtime.Literal elem);
        void inverse_remove(org.xowl.infra.lang.runtime.Literal elem);
    }
    valueLiteral __getImplOfvalueLiteral();
    boolean setValueLiteral(org.xowl.infra.lang.runtime.Literal elem);
    org.xowl.infra.lang.runtime.Literal getValueLiteral();
    // </editor-fold>
}
