/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.owl2;

public interface Annotation_OR_AnnotationAssertion {
    // <editor-fold defaultstate="collapsed" desc="Property annotValue">
    public static interface annotValue {
        boolean check_contains(org.xowl.lang.owl2.AnnotationValue elem);
        boolean user_check_add(org.xowl.lang.owl2.AnnotationValue elem);
        boolean user_check_remove(org.xowl.lang.owl2.AnnotationValue elem);
        boolean user_check_replace(org.xowl.lang.owl2.AnnotationValue oldElem, org.xowl.lang.owl2.AnnotationValue  newElem);
        void user_add(org.xowl.lang.owl2.AnnotationValue elem);
        void user_remove(org.xowl.lang.owl2.AnnotationValue elem);
        boolean inverse_check_add(org.xowl.lang.owl2.AnnotationValue elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.AnnotationValue elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.AnnotationValue oldElem, org.xowl.lang.owl2.AnnotationValue  newElem);
        void inverse_add(org.xowl.lang.owl2.AnnotationValue elem);
        void inverse_remove(org.xowl.lang.owl2.AnnotationValue elem);
    }
    annotValue __getImplOfannotValue();
    boolean setAnnotValue(org.xowl.lang.owl2.AnnotationValue elem);
    org.xowl.lang.owl2.AnnotationValue getAnnotValue();
    // </editor-fold>
}
