/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.owl2;

public interface Axiom_OR_Statement {
    // <editor-fold defaultstate="collapsed" desc="Property file">
    public static interface file {
        boolean check_contains(java.lang.String elem);
        boolean user_check_add(java.lang.String elem);
        boolean user_check_remove(java.lang.String elem);
        boolean user_check_replace(java.lang.String oldElem, java.lang.String  newElem);
        void user_add(java.lang.String elem);
        void user_remove(java.lang.String elem);
        boolean inverse_check_add(java.lang.String elem);
        boolean inverse_check_remove(java.lang.String elem);
        boolean inverse_check_replace(java.lang.String oldElem, java.lang.String  newElem);
        void inverse_add(java.lang.String elem);
        void inverse_remove(java.lang.String elem);
    }
    file __getImplOffile();
    boolean setFile(java.lang.String elem);
    java.lang.String getFile();
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Property line">
    public static interface line {
        boolean check_contains(java.lang.Integer elem);
        boolean user_check_add(java.lang.Integer elem);
        boolean user_check_remove(java.lang.Integer elem);
        boolean user_check_replace(java.lang.Integer oldElem, java.lang.Integer  newElem);
        void user_add(java.lang.Integer elem);
        void user_remove(java.lang.Integer elem);
        boolean inverse_check_add(java.lang.Integer elem);
        boolean inverse_check_remove(java.lang.Integer elem);
        boolean inverse_check_replace(java.lang.Integer oldElem, java.lang.Integer  newElem);
        void inverse_add(java.lang.Integer elem);
        void inverse_remove(java.lang.Integer elem);
    }
    line __getImplOfline();
    boolean setLine(java.lang.Integer elem);
    java.lang.Integer getLine();
    // </editor-fold>
}
