/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.owl2;

public interface CardinalityRestriction extends org.xowl.lang.owl2.ClassRestriction, org.xowl.lang.owl2.ClassExpression, org.xowl.lang.owl2.Expression {
    // <editor-fold defaultstate="collapsed" desc="Property cardinality">
    public static interface cardinality {
        boolean check_contains(org.xowl.lang.owl2.LiteralExpression elem);
        boolean user_check_add(org.xowl.lang.owl2.LiteralExpression elem);
        boolean user_check_remove(org.xowl.lang.owl2.LiteralExpression elem);
        boolean user_check_replace(org.xowl.lang.owl2.LiteralExpression oldElem, org.xowl.lang.owl2.LiteralExpression  newElem);
        void user_add(org.xowl.lang.owl2.LiteralExpression elem);
        void user_remove(org.xowl.lang.owl2.LiteralExpression elem);
        boolean inverse_check_add(org.xowl.lang.owl2.LiteralExpression elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.LiteralExpression elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.LiteralExpression oldElem, org.xowl.lang.owl2.LiteralExpression  newElem);
        void inverse_add(org.xowl.lang.owl2.LiteralExpression elem);
        void inverse_remove(org.xowl.lang.owl2.LiteralExpression elem);
    }
    cardinality __getImplOfcardinality();
    boolean setCardinality(org.xowl.lang.owl2.LiteralExpression elem);
    org.xowl.lang.owl2.LiteralExpression getCardinality();
    // </editor-fold>
}
