/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.owl2;

public class DataPropertySequence implements org.xowl.lang.owl2.DataPropertySequenceExpression, org.xowl.lang.owl2.SequenceExpression {
    // <editor-fold defaultstate="collapsed" desc="Property dataPropertyElements">
    public static interface dataPropertyElements {
        boolean check_contains(org.xowl.lang.owl2.DataPropertyElement elem);
        boolean user_check_add(org.xowl.lang.owl2.DataPropertyElement elem);
        boolean user_check_remove(org.xowl.lang.owl2.DataPropertyElement elem);
        boolean user_check_replace(org.xowl.lang.owl2.DataPropertyElement oldElem, org.xowl.lang.owl2.DataPropertyElement  newElem);
        void user_add(org.xowl.lang.owl2.DataPropertyElement elem);
        void user_remove(org.xowl.lang.owl2.DataPropertyElement elem);
        boolean inverse_check_add(org.xowl.lang.owl2.DataPropertyElement elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.DataPropertyElement elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.DataPropertyElement oldElem, org.xowl.lang.owl2.DataPropertyElement  newElem);
        void inverse_add(org.xowl.lang.owl2.DataPropertyElement elem);
        void inverse_remove(org.xowl.lang.owl2.DataPropertyElement elem);
    }
    private static class dataPropertyElements_impl implements org.xowl.lang.owl2.DataPropertySequence.dataPropertyElements {
        private org.xowl.lang.owl2.DataPropertySequence domain;
        private java.util.List<org.xowl.lang.owl2.DataPropertyElement> data;
        public java.util.Collection<org.xowl.lang.owl2.DataPropertyElement> get_raw() { return new java.util.ArrayList<org.xowl.lang.owl2.DataPropertyElement>(data); }
        public java.util.Collection<org.xowl.lang.owl2.DataPropertyElement> get() { return new java.util.ArrayList<org.xowl.lang.owl2.DataPropertyElement>(data); }
        private boolean check_card(int modifier) {
            int card = data.size() + 0 + modifier;
            return (card >= 0 && card <= 2147483647);
        }
        @Override public boolean check_contains(org.xowl.lang.owl2.DataPropertyElement elem) { return (data.contains(elem)); }
        public boolean simple_check_add(org.xowl.lang.owl2.DataPropertyElement elem) {
            if (check_contains(elem)) return false;
            if (!check_card(1)) return false;
            return true;
        }
        public boolean simple_check_remove(org.xowl.lang.owl2.DataPropertyElement elem) {
            if (!check_contains(elem)) return false;
            if (!check_card(-1)) return false;
            return true;
        }
        public boolean simple_check_replace(org.xowl.lang.owl2.DataPropertyElement oldElem, org.xowl.lang.owl2.DataPropertyElement  newElem) {
            if (check_contains(newElem)) return false;
            if (!check_contains(oldElem)) return false;
            return true;
        }
        public void simple_add(org.xowl.lang.owl2.DataPropertyElement elem) {
            data.add(elem);
        }
        public void simple_remove(org.xowl.lang.owl2.DataPropertyElement elem) {
            data.remove(elem);
        }
        private boolean tree_check_add(org.xowl.lang.owl2.DataPropertyElement elem) {
            if (!simple_check_add(elem)) return false;
            return true;
        }
        private boolean tree_check_remove(org.xowl.lang.owl2.DataPropertyElement elem) {
            if (!simple_check_remove(elem)) return false;
            return true;
        }
        private boolean tree_check_replace(org.xowl.lang.owl2.DataPropertyElement oldElem, org.xowl.lang.owl2.DataPropertyElement  newElem) {
            if (!simple_check_replace(oldElem, newElem)) return false;
            return true;
        }
        private void tree_add(org.xowl.lang.owl2.DataPropertyElement elem) {
            simple_add(elem);
        }
        private void tree_remove(org.xowl.lang.owl2.DataPropertyElement elem) {
            simple_remove(elem);
        }
        @Override public boolean user_check_add(org.xowl.lang.owl2.DataPropertyElement elem) {
            return tree_check_add(elem);
        }
        @Override public boolean user_check_remove(org.xowl.lang.owl2.DataPropertyElement elem) {
            return tree_check_remove(elem);
        }
        @Override public boolean user_check_replace(org.xowl.lang.owl2.DataPropertyElement oldElem, org.xowl.lang.owl2.DataPropertyElement  newElem) {
            return tree_check_replace(oldElem, newElem);
        }
        @Override public void user_add(org.xowl.lang.owl2.DataPropertyElement elem) {
            tree_add(elem);
        }
        @Override public void user_remove(org.xowl.lang.owl2.DataPropertyElement elem) {
            tree_remove(elem);
        }
        @Override public boolean inverse_check_add(org.xowl.lang.owl2.DataPropertyElement elem) {
            return tree_check_add(elem);
        }
        @Override public boolean inverse_check_remove(org.xowl.lang.owl2.DataPropertyElement elem) {
            return tree_check_remove(elem);
        }
        @Override public boolean inverse_check_replace(org.xowl.lang.owl2.DataPropertyElement oldElem, org.xowl.lang.owl2.DataPropertyElement  newElem) {
            return tree_check_replace(oldElem, newElem);
        }
        @Override public void inverse_add(org.xowl.lang.owl2.DataPropertyElement elem) {
            tree_add(elem);
        }
        @Override public void inverse_remove(org.xowl.lang.owl2.DataPropertyElement elem) {
            tree_remove(elem);
        }
        public dataPropertyElements_impl(org.xowl.lang.owl2.DataPropertySequence domain) {
            this.domain = domain;
            this.data = new java.util.ArrayList<org.xowl.lang.owl2.DataPropertyElement>();
        }
    }
    private dataPropertyElements_impl dataDataPropertyElements;
    public org.xowl.lang.owl2.DataPropertySequence.dataPropertyElements __getImplOfdataPropertyElements() { return dataDataPropertyElements; }
    public boolean addDataPropertyElements(org.xowl.lang.owl2.DataPropertyElement elem) {
        if (!dataDataPropertyElements.user_check_add(elem)) return false;
        dataDataPropertyElements.user_add(elem);
        return true;
    }
    public boolean removeDataPropertyElements(org.xowl.lang.owl2.DataPropertyElement elem) {
        if (!dataDataPropertyElements.user_check_remove(elem)) return false;
        dataDataPropertyElements.user_remove(elem);
        return true;
    }
    public java.util.Collection<org.xowl.lang.owl2.DataPropertyElement> getAllDataPropertyElements() { return dataDataPropertyElements.get(); }
    // </editor-fold>

    public DataPropertySequence() {
        dataDataPropertyElements = new dataPropertyElements_impl(this);
    }
    
}
