/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.owl2;

public interface DisjointDataProperties_OR_EquivalentDataProperties_OR_HasKey_OR_NAryDataPropertyRestriction {
    // <editor-fold defaultstate="collapsed" desc="Property dataPropertySeq">
    public static interface dataPropertySeq {
        boolean check_contains(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
        boolean user_check_add(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
        boolean user_check_remove(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
        boolean user_check_replace(org.xowl.lang.owl2.DataPropertySequenceExpression oldElem, org.xowl.lang.owl2.DataPropertySequenceExpression  newElem);
        void user_add(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
        void user_remove(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
        boolean inverse_check_add(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
        boolean inverse_check_remove(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
        boolean inverse_check_replace(org.xowl.lang.owl2.DataPropertySequenceExpression oldElem, org.xowl.lang.owl2.DataPropertySequenceExpression  newElem);
        void inverse_add(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
        void inverse_remove(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
    }
    dataPropertySeq __getImplOfdataPropertySeq();
    boolean setDataPropertySeq(org.xowl.lang.owl2.DataPropertySequenceExpression elem);
    org.xowl.lang.owl2.DataPropertySequenceExpression getDataPropertySeq();
    // </editor-fold>
}
