/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.owl2;

public interface IndividualAxiom extends org.xowl.lang.owl2.Axiom, org.xowl.lang.owl2.Annotation_OR_Axiom_OR_Ontology, org.xowl.lang.owl2.Axiom_OR_Statement {
}
