/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.owl2;

public class ObjectHasValue implements org.xowl.lang.owl2.ObjectPropertyRestriction, org.xowl.lang.owl2.ClassAssertion_OR_DataPropertyAssertion_OR_IndividualElement_OR_NegativeDataPropertyAssertion_OR_Ne3, org.xowl.lang.owl2.ClassRestriction, org.xowl.lang.owl2.AsymmetricObjectProperty_OR_FunctionalObjectProperty_OR_InverseFunctionalObjectProperty_OR_InverseO0, org.xowl.lang.owl2.ClassExpression, org.xowl.lang.owl2.Expression {
    // <editor-fold defaultstate="collapsed" desc="Property objectProperty">
    private static class objectProperty_impl implements org.xowl.lang.owl2.AsymmetricObjectProperty_OR_FunctionalObjectProperty_OR_InverseFunctionalObjectProperty_OR_InverseO0.objectProperty {
        private org.xowl.lang.owl2.ObjectHasValue domain;
        private org.xowl.lang.owl2.ObjectPropertyExpression data;
        public org.xowl.lang.owl2.ObjectPropertyExpression get_raw() { return data; }
        public org.xowl.lang.owl2.ObjectPropertyExpression get() { return data; }
        private boolean check_card(int modifier) {
            int card = modifier + 0;
            if (data != null) card++;
            return (card >= 0 && card <= 1);
        }
        @Override public boolean check_contains(org.xowl.lang.owl2.ObjectPropertyExpression elem) { return (data == elem); }
        public boolean simple_check_add(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            if (check_contains(elem)) return false;
            if (!check_card(1)) return false;
            return true;
        }
        public boolean simple_check_remove(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            if (!check_contains(elem)) return false;
            if (!check_card(-1)) return false;
            return true;
        }
        public boolean simple_check_replace(org.xowl.lang.owl2.ObjectPropertyExpression oldElem, org.xowl.lang.owl2.ObjectPropertyExpression  newElem) {
            if (check_contains(newElem)) return false;
            if (!check_contains(oldElem)) return false;
            return true;
        }
        public void simple_add(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            data = elem;
        }
        public void simple_remove(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            data = null;
        }
        private boolean tree_check_add(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            if (!simple_check_add(elem)) return false;
            return true;
        }
        private boolean tree_check_remove(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            if (!simple_check_remove(elem)) return false;
            return true;
        }
        private boolean tree_check_replace(org.xowl.lang.owl2.ObjectPropertyExpression oldElem, org.xowl.lang.owl2.ObjectPropertyExpression  newElem) {
            if (!simple_check_replace(oldElem, newElem)) return false;
            return true;
        }
        private void tree_add(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            simple_add(elem);
        }
        private void tree_remove(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            simple_remove(elem);
        }
        @Override public boolean user_check_add(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            return tree_check_add(elem);
        }
        @Override public boolean user_check_remove(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            return tree_check_remove(elem);
        }
        @Override public boolean user_check_replace(org.xowl.lang.owl2.ObjectPropertyExpression oldElem, org.xowl.lang.owl2.ObjectPropertyExpression  newElem) {
            return tree_check_replace(oldElem, newElem);
        }
        @Override public void user_add(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            tree_add(elem);
        }
        @Override public void user_remove(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            tree_remove(elem);
        }
        @Override public boolean inverse_check_add(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            return tree_check_add(elem);
        }
        @Override public boolean inverse_check_remove(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            return tree_check_remove(elem);
        }
        @Override public boolean inverse_check_replace(org.xowl.lang.owl2.ObjectPropertyExpression oldElem, org.xowl.lang.owl2.ObjectPropertyExpression  newElem) {
            return tree_check_replace(oldElem, newElem);
        }
        @Override public void inverse_add(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            tree_add(elem);
        }
        @Override public void inverse_remove(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
            tree_remove(elem);
        }
        public objectProperty_impl(org.xowl.lang.owl2.ObjectHasValue domain) {
            this.domain = domain;
        }
    }
    private objectProperty_impl dataObjectProperty;
    public org.xowl.lang.owl2.AsymmetricObjectProperty_OR_FunctionalObjectProperty_OR_InverseFunctionalObjectProperty_OR_InverseO0.objectProperty __getImplOfobjectProperty() { return dataObjectProperty; }
    public boolean setObjectProperty(org.xowl.lang.owl2.ObjectPropertyExpression elem) {
        if (dataObjectProperty.get() != null) {
            if (elem == null) {
                if (!dataObjectProperty.user_check_remove(dataObjectProperty.get())) return false;
                dataObjectProperty.user_remove(dataObjectProperty.get());
            } else {
                if (!dataObjectProperty.user_check_replace(dataObjectProperty.get(), elem)) return false;
                dataObjectProperty.user_remove(dataObjectProperty.get());
                dataObjectProperty.user_add(elem);
            }
        } else {
            if (elem == null) return true;
            if (!dataObjectProperty.user_check_add(elem)) return false;
            dataObjectProperty.user_add(elem);
        }
        return true;
    }
    public org.xowl.lang.owl2.ObjectPropertyExpression getObjectProperty() { return dataObjectProperty.get(); }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Property individual">
    private static class individual_impl implements org.xowl.lang.owl2.ClassAssertion_OR_DataPropertyAssertion_OR_IndividualElement_OR_NegativeDataPropertyAssertion_OR_Ne3.individual {
        private org.xowl.lang.owl2.ObjectHasValue domain;
        private org.xowl.lang.owl2.IndividualExpression data;
        public org.xowl.lang.owl2.IndividualExpression get_raw() { return data; }
        public org.xowl.lang.owl2.IndividualExpression get() { return data; }
        private boolean check_card(int modifier) {
            int card = modifier + 0;
            if (data != null) card++;
            return (card >= 0 && card <= 1);
        }
        @Override public boolean check_contains(org.xowl.lang.owl2.IndividualExpression elem) { return (data == elem); }
        public boolean simple_check_add(org.xowl.lang.owl2.IndividualExpression elem) {
            if (check_contains(elem)) return false;
            if (!check_card(1)) return false;
            return true;
        }
        public boolean simple_check_remove(org.xowl.lang.owl2.IndividualExpression elem) {
            if (!check_contains(elem)) return false;
            if (!check_card(-1)) return false;
            return true;
        }
        public boolean simple_check_replace(org.xowl.lang.owl2.IndividualExpression oldElem, org.xowl.lang.owl2.IndividualExpression  newElem) {
            if (check_contains(newElem)) return false;
            if (!check_contains(oldElem)) return false;
            return true;
        }
        public void simple_add(org.xowl.lang.owl2.IndividualExpression elem) {
            data = elem;
        }
        public void simple_remove(org.xowl.lang.owl2.IndividualExpression elem) {
            data = null;
        }
        private boolean tree_check_add(org.xowl.lang.owl2.IndividualExpression elem) {
            if (!simple_check_add(elem)) return false;
            return true;
        }
        private boolean tree_check_remove(org.xowl.lang.owl2.IndividualExpression elem) {
            if (!simple_check_remove(elem)) return false;
            return true;
        }
        private boolean tree_check_replace(org.xowl.lang.owl2.IndividualExpression oldElem, org.xowl.lang.owl2.IndividualExpression  newElem) {
            if (!simple_check_replace(oldElem, newElem)) return false;
            return true;
        }
        private void tree_add(org.xowl.lang.owl2.IndividualExpression elem) {
            simple_add(elem);
        }
        private void tree_remove(org.xowl.lang.owl2.IndividualExpression elem) {
            simple_remove(elem);
        }
        @Override public boolean user_check_add(org.xowl.lang.owl2.IndividualExpression elem) {
            return tree_check_add(elem);
        }
        @Override public boolean user_check_remove(org.xowl.lang.owl2.IndividualExpression elem) {
            return tree_check_remove(elem);
        }
        @Override public boolean user_check_replace(org.xowl.lang.owl2.IndividualExpression oldElem, org.xowl.lang.owl2.IndividualExpression  newElem) {
            return tree_check_replace(oldElem, newElem);
        }
        @Override public void user_add(org.xowl.lang.owl2.IndividualExpression elem) {
            tree_add(elem);
        }
        @Override public void user_remove(org.xowl.lang.owl2.IndividualExpression elem) {
            tree_remove(elem);
        }
        @Override public boolean inverse_check_add(org.xowl.lang.owl2.IndividualExpression elem) {
            return tree_check_add(elem);
        }
        @Override public boolean inverse_check_remove(org.xowl.lang.owl2.IndividualExpression elem) {
            return tree_check_remove(elem);
        }
        @Override public boolean inverse_check_replace(org.xowl.lang.owl2.IndividualExpression oldElem, org.xowl.lang.owl2.IndividualExpression  newElem) {
            return tree_check_replace(oldElem, newElem);
        }
        @Override public void inverse_add(org.xowl.lang.owl2.IndividualExpression elem) {
            tree_add(elem);
        }
        @Override public void inverse_remove(org.xowl.lang.owl2.IndividualExpression elem) {
            tree_remove(elem);
        }
        public individual_impl(org.xowl.lang.owl2.ObjectHasValue domain) {
            this.domain = domain;
        }
    }
    private individual_impl dataIndividual;
    public org.xowl.lang.owl2.ClassAssertion_OR_DataPropertyAssertion_OR_IndividualElement_OR_NegativeDataPropertyAssertion_OR_Ne3.individual __getImplOfindividual() { return dataIndividual; }
    public boolean setIndividual(org.xowl.lang.owl2.IndividualExpression elem) {
        if (dataIndividual.get() != null) {
            if (elem == null) {
                if (!dataIndividual.user_check_remove(dataIndividual.get())) return false;
                dataIndividual.user_remove(dataIndividual.get());
            } else {
                if (!dataIndividual.user_check_replace(dataIndividual.get(), elem)) return false;
                dataIndividual.user_remove(dataIndividual.get());
                dataIndividual.user_add(elem);
            }
        } else {
            if (elem == null) return true;
            if (!dataIndividual.user_check_add(elem)) return false;
            dataIndividual.user_add(elem);
        }
        return true;
    }
    public org.xowl.lang.owl2.IndividualExpression getIndividual() { return dataIndividual.get(); }
    // </editor-fold>

    public ObjectHasValue() {
        dataObjectProperty = new objectProperty_impl(this);
        dataIndividual = new individual_impl(this);
    }
    
}
