/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.owl2;

public interface SequenceElement {
    // <editor-fold defaultstate="collapsed" desc="Property index">
    public static interface index {
        boolean check_contains(java.lang.Integer elem);
        boolean user_check_add(java.lang.Integer elem);
        boolean user_check_remove(java.lang.Integer elem);
        boolean user_check_replace(java.lang.Integer oldElem, java.lang.Integer  newElem);
        void user_add(java.lang.Integer elem);
        void user_remove(java.lang.Integer elem);
        boolean inverse_check_add(java.lang.Integer elem);
        boolean inverse_check_remove(java.lang.Integer elem);
        boolean inverse_check_replace(java.lang.Integer oldElem, java.lang.Integer  newElem);
        void inverse_add(java.lang.Integer elem);
        void inverse_remove(java.lang.Integer elem);
    }
    index __getImplOfindex();
    boolean setIndex(java.lang.Integer elem);
    java.lang.Integer getIndex();
    // </editor-fold>
}
