/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.runtime;

public interface DataPropertyRestriction extends org.xowl.lang.runtime.ClassRestriction {
    // <editor-fold defaultstate="collapsed" desc="Property dataProperty">
    public static interface dataProperty {
        boolean check_contains(org.xowl.lang.runtime.DataProperty elem);
        boolean user_check_add(org.xowl.lang.runtime.DataProperty elem);
        boolean user_check_remove(org.xowl.lang.runtime.DataProperty elem);
        boolean user_check_replace(org.xowl.lang.runtime.DataProperty oldElem, org.xowl.lang.runtime.DataProperty  newElem);
        void user_add(org.xowl.lang.runtime.DataProperty elem);
        void user_remove(org.xowl.lang.runtime.DataProperty elem);
        boolean inverse_check_add(org.xowl.lang.runtime.DataProperty elem);
        boolean inverse_check_remove(org.xowl.lang.runtime.DataProperty elem);
        boolean inverse_check_replace(org.xowl.lang.runtime.DataProperty oldElem, org.xowl.lang.runtime.DataProperty  newElem);
        void inverse_add(org.xowl.lang.runtime.DataProperty elem);
        void inverse_remove(org.xowl.lang.runtime.DataProperty elem);
    }
    dataProperty __getImplOfdataProperty();
    boolean setDataProperty(org.xowl.lang.runtime.DataProperty elem);
    org.xowl.lang.runtime.DataProperty getDataProperty();
    // </editor-fold>
}
