/* This file has been generated by:
   xOWL Code Generator
*/
package org.xowl.lang.runtime;

public interface ObjectPropertyRestriction extends org.xowl.lang.runtime.ClassRestriction {
    // <editor-fold defaultstate="collapsed" desc="Property objectProperty">
    public static interface objectProperty {
        boolean check_contains(org.xowl.lang.runtime.ObjectProperty elem);
        boolean user_check_add(org.xowl.lang.runtime.ObjectProperty elem);
        boolean user_check_remove(org.xowl.lang.runtime.ObjectProperty elem);
        boolean user_check_replace(org.xowl.lang.runtime.ObjectProperty oldElem, org.xowl.lang.runtime.ObjectProperty  newElem);
        void user_add(org.xowl.lang.runtime.ObjectProperty elem);
        void user_remove(org.xowl.lang.runtime.ObjectProperty elem);
        boolean inverse_check_add(org.xowl.lang.runtime.ObjectProperty elem);
        boolean inverse_check_remove(org.xowl.lang.runtime.ObjectProperty elem);
        boolean inverse_check_replace(org.xowl.lang.runtime.ObjectProperty oldElem, org.xowl.lang.runtime.ObjectProperty  newElem);
        void inverse_add(org.xowl.lang.runtime.ObjectProperty elem);
        void inverse_remove(org.xowl.lang.runtime.ObjectProperty elem);
    }
    objectProperty __getImplOfobjectProperty();
    boolean setObjectProperty(org.xowl.lang.runtime.ObjectProperty elem);
    org.xowl.lang.runtime.ObjectProperty getObjectProperty();
    // </editor-fold>
}
